---
- hosts: all
  gather_facts: yes
  pre_tasks:
    - name: Limit to Archlinux and NixOS
      fail:
        msg: "{{ ansible_distribution }} is not supported with this tag."
      when: (ansible_distribution != "Archlinux") and
            (ansible_distribution != "NixOS")

- hosts: cli:desktop
  roles:
    - role: fish
      tags: fish
    - role: neovim
      tags: neovim
    - role: screen
      tags: screen
    - role: git
      tags: git,cli
    - role: userbin
      tags: userbin

- hosts: desktop
  roles:
    - role: ssh-agent
      tags: ssh-agent
      when: ansible_distribution == "Archlinux" and ansible_user_id != 'root'
    - role: gtk
      tags: gtk
      when: ansible_user_id != 'root'
    - role: sway
      tags: sway
      when: ansible_user_id != 'root'
    - role: waybar
      tags: waybar
      when: ansible_user_id != 'root'
    - role: wofi
      tags: wofi
      when: ansible_user_id != 'root'
    - role: mako
      tags: mako
      when: ansible_user_id != 'root'
    - role: kitty
      tags: kitty
      when: ansible_user_id != 'root'
