"pathogen
execute pathogen#infect()

" lines numbers
" set nu
syntax on
filetype plugin indent on
set background=dark
set mouse=r
set ruler		" show the cursor position all the time
set autoindent		" always set autoindenting on
set wildmenu

" tab 4 spaces
set tabstop=8 softtabstop=0 expandtab shiftwidth=4 smarttab

" brackets highlight color
autocmd VimEnter,Colorscheme * :hi MatchParen cterm=none ctermbg=white ctermfg=black

" remember last cursor place
au BufReadPost * if line("'\"") > 0|if line("'\"") <= line("$")|exe("norm '\"")|else|exe "norm $"|endif|endif

" airline
let g:airline_powerline_fonts = 1
if !exists('g:airline_symbols')
      let g:airline_symbols = {}
endif
let g:airline_symbols.space = "\ua0"
"let g:airline#extensions#tabline#enabled = 1
"let g:airline#extensions#tabline#show_buffers = 0
let g:airline_theme = 'minimalist'
