# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/jessie64"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    #vb.gui = true
  
    # Customize the amount of memory on the VM:
    vb.name = "debian_dotfiles"
    vb.memory = "1024"
    vb.cpus = 1
  end

  config.vm.provision "shell", inline: <<-SHELL
    echo 'deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main' >> /etc/apt/sources.list
    apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367
    apt update
    apt install git ansible -y
    # HOSTNAME
    echo "debian" > /etc/hostname
    echo "127.0.0.1       localhost localhost.localdomain debian" > /etc/hosts
    hostname debian
  SHELL

  $script = <<-SCRIPT
  # PREP
  touch ~/.viminfo; rm ~/.viminfo
  touch ~/.vimrc; rm ~/.vimrc
  # EXEC
  git clone --recursive https://github.com/eoli3n/dotfiles
  cd dotfiles
  git submodule update --init --recursive
  ./install.sh server
  echo -e "vagrant\n/usr/bin/zsh" | chsh
  SCRIPT

  config.vm.provision "shell", inline: $script, privileged: false
end
