# -*- mode: ruby -*-
# vi: set ft=ruby :



Vagrant.configure("2") do |config|
  config.vm.box = "debian/jessie64"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    #vb.gui = true
  
    # Customize the amount of memory on the VM:
    vb.name = "debian_dotfiles"
    vb.memory = "1024"
    vb.cpus = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt install git python-pip -y
    pip install ansible -U
  SHELL

  $script = <<-SCRIPT
  # PREP
  touch ~/.viminfo; rm ~/.viminfo
  touch ~/.vimrc; rm ~/.vimrc
  # EXEC
  git clone --recursive https://github.com/eoli3n/dotfiles
  cd dotfiles
  git submodule update --init --recursive
  ./install.sh desktop
  echo -e "vagrant\n/usr/bin/zsh" | chsh
  SCRIPT

  config.vm.provision "shell", inline: $script, privileged: false
end
