# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "terrywang/archlinux"
  config.vm.provision "shell", inline: <<-SHELL
    pacman -Syu --noconfirm
    pacman -S ansible --noconfirm
    pacman -R cowsay --noconfirm
  SHELL

  $script = <<-SCRIPT
  git clone --recursive https://github.com/eoli3n/dotfiles
  cd dotfiles
  git checkout dev
  git submodule update --init --recursive
  ./install.sh desktop
  SCRIPT

  config.vm.provision "shell", inline: $script, privileged: false
end
