# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "terrywang/archlinux"
  config.vm.provision "shell", inline: <<-SHELL
    pacman -Syu --no-confirm
    pacman -S git --no-confirm
    git clone --recursive https://github.com/eoli3n/dotfiles
    cd dotfiles
    git checkout dev
    ./install.sh desktop
  SHELL
end
